// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Session struct {
	ID        uuid.UUID
	UserID    int32
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserAgent sql.NullString
	IpAddress pqtype.Inet
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
