// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           int32
	PublicID     uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Vault struct {
	UserID    int32
	Vault     []byte
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
