// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault.sql

package db

import (
	"context"
)

const getVaultByUserID = `-- name: GetVaultByUserID :one
SELECT user_id, vault, created_at, updated_at
FROM vaults
WHERE user_id = $1
`

func (q *Queries) GetVaultByUserID(ctx context.Context, userID int32) (Vault, error) {
	row := q.db.QueryRowContext(ctx, getVaultByUserID, userID)
	var i Vault
	err := row.Scan(
		&i.UserID,
		&i.Vault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVaultByUserID = `-- name: InsertVaultByUserID :one
INSERT INTO vaults (user_id, vault)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET
    vault = EXCLUDED.vault,
    updated_at = NOW()
RETURNING user_id, vault, created_at, updated_at
`

type InsertVaultByUserIDParams struct {
	UserID int32
	Vault  []byte
}

func (q *Queries) InsertVaultByUserID(ctx context.Context, arg InsertVaultByUserIDParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, insertVaultByUserID, arg.UserID, arg.Vault)
	var i Vault
	err := row.Scan(
		&i.UserID,
		&i.Vault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
