/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access and refresh tokens */
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue access and refresh tokens */
        post: operations["IssueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["GetCurrentUser"];
        put?: never;
        /** Create a new user */
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserRequest: {
            /** Format: email */
            email: string;
            name: string;
            /** Format: password */
            password: string;
        };
        ErrorResponse: {
            /** @example 500 */
            code: number;
            /** @example Internal server error */
            message: string;
        };
        LoginRequest: {
            /** @description Unique identifier for the client device (used for token management) */
            deviceID: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenResponse: {
            /** @description JWT access token */
            accessToken: string;
            /**
             * @description Access token expiration time in seconds
             * @example 900
             */
            expiresIn: number;
            /** @description Refresh token */
            refreshToken: string;
            /** @example Bearer */
            tokenType?: string;
        };
        User: {
            /**
             * Format: date-time
             * @example 2026-02-23T12:00:00Z
             */
            CreatedAt?: string;
            /**
             * Format: email
             * @example john@example.com
             */
            Email?: string;
            /**
             * Format: int32
             * @example 1
             */
            ID?: number;
            /** @example John Doe */
            Name?: string;
        };
        UserResponse: {
            email: string;
            id: string;
            username: string;
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 400,
                 *       "message": "Missing required field 'name'"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 500,
                 *       "message": "Something went wrong on the server"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCreateUserRequest = components['schemas']['CreateUserRequest'];
export type SchemaErrorResponse = components['schemas']['ErrorResponse'];
export type SchemaLoginRequest = components['schemas']['LoginRequest'];
export type SchemaTokenResponse = components['schemas']['TokenResponse'];
export type SchemaUser = components['schemas']['User'];
export type SchemaUserResponse = components['schemas']['UserResponse'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponseInternalServerError = components['responses']['InternalServerError'];
export type $defs = Record<string, never>;
export interface operations {
    RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens refreshed successfully */
            200: {
                headers: {
                    /** @description Updated HttpOnly cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 401,
                     *       "message": "Invalid or expired refresh token"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    IssueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Tokens issued successfully */
            200: {
                headers: {
                    /** @description HttpOnly cookies for access and refresh tokens */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 401,
                     *       "message": "Invalid email or password"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 401,
                     *       "message": "User not authenticated"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
